name: Estrutura ANAC

on:
  schedule:
    - cron: '0 0 1 * *' # roda dia 1 todo mês
  workflow_dispatch:

jobs:
  gerar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gerar TSV com Bash + xmllint
        run: |
          URL="https://estruturaorganizacional.dados.gov.br/doc/estrutura-organizacional/completa.xml?codigoPoder=1&codigoEsfera=1&codigoUnidade=86144&retornarOrgaoEntidadeVinculados=SIM"
          curl -s "$URL" -o estrutura.xml
          {
            echo -e "Sigla\tNome\tCompetencia\tUF\tMunicipio\tCEP\tCodigoUnidade\tCodigoUnidadePai"
            xmllint --xpath "//unidades" estrutura.xml | \
            xmllint --format - | \
            awk -F'[<>]' '
              /<sigla>/        {sigla=$3}
              /<nome>/         {nome=$3}
              /<competencia>/  {gsub(/\n/," ",$3); gsub(/\t/," ",$3); comp=$3}
              /<uf>/           {uf=$3}
              /<municipio>/    {mun=$3}
              /<cep>/          {cep=$3}
              /<codigoUnidade>/    {cod=$3; sub(".*/","",cod)}
              /<codigoUnidadePai>/ {pai=$3; sub(".*/","",pai)}
              /<\/unidades>/ {
                print sigla "\t" nome "\t" comp "\t" uf "\t" mun "\t" cep "\t" cod "\t" pai;
                sigla=nome=comp=uf=mun=cep=cod=pai="";
              }'
          } > anac-estrutura.tsv

      - name: Commit e Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add anac-estrutura.tsv
          if ! git diff --cached --quiet; then
            git commit -m "Atualização automática da estrutura ANAC"
            git push
          else
            echo "✅ Sem mudanças"
