name: Estrutura ANAC 2 JSONLD

on:
  schedule:
    - cron: '0 0 1 * *' # todo dia 1º do mês, à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Baixar XML da ANAC
        run: |
          mkdir -p tmp
          curl -s "https://estruturaorganizacional.dados.gov.br/doc/estrutura-organizacional/completa.xml?codigoPoder=1&codigoEsfera=1&codigoUnidade=86144&retornarOrgaoEntidadeVinculados=SIM" -o tmp/estrutura.xml

      - name: Converter XML para JSON-LD com siglaCompleta
        run: |
          deno run -A --unstable https://deno.land/x/flat@0.0.20/mod.ts \
            --input tmp/estrutura.xml \
            --format xml \
            --output anac-estrutura.jsonld \
            --context '{
              "@context": {
                "sigla": "http://schema.org/alternateName",
                "siglaCompleta": "http://schema.org/identifier",
                "nome": "http://schema.org/name",
                "competencia": "http://schema.org/description",
                "uf": "http://schema.org/addressRegion",
                "municipio": "http://schema.org/addressLocality",
                "cep": "http://schema.org/postalCode",
                "codigoUnidade": "https://dados.gov.br/def/unidade",
                "codigoUnidadePai": "https://dados.gov.br/def/unidadePai"
              }
            }' \
            --transform 'for (let u of $){ 
              let byCode = {}; 
              for (let d of $) byCode[d.codigoUnidade] = d; 
              for (let d of $){
                let path = [];
                let cur = d;
                let seen = new Set();
                while(cur && cur.codigoUnidade && !seen.has(cur.codigoUnidade)){
                  seen.add(cur.codigoUnidade);
                  path.unshift(cur.sigla || cur.nome);
                  cur = byCode[cur.codigoUnidadePai];
                }
                d.siglaCompleta = path.join("/");
                if(d.sigla && d.sigla.startsWith("NURAC")){
                  let parts = d.nome.split(" ");
                  let city = parts[6] || "";
                  let state = parts[7] || "";
                  d.sigla = `NURAC ${city} ${state}`.trim();
                  let pcs = d.siglaCompleta.split("/");
                  pcs[pcs.length-1] = d.sigla;
                  d.siglaCompleta = pcs.join("/");
                }
              }
            }'

      - name: Commit se houver alterações
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add anac-estrutura.jsonld
          if ! git diff --cached --quiet; then
            git commit -m "Atualização automática da estrutura ANAC"
            git push
          else
            echo "✅ Sem alterações"
