name: Estrutura ANAC

on:
  schedule:
    - cron: "0 0 1 * *"   # roda todo dia 1 do mês, à meia-noite UTC
  workflow_dispatch:       # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v4

      - name: Configurar python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Rodar o script
        run: |
          python scripts/estrutura.py

      - name: Commit e push de arquivos, se houver mudanças
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add :/
          COMMIT_MESSAGE="$(date +"%Y-%m-%d %H:%M")"
          git commit -m "$COMMIT_MESSAGE" || exit 0
          git pull --rebase
          git push
