name: Extrair Portarias ANAC

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'  # Executa todo domingo às 03:00 AM UTC

jobs:
  extrair-portarias:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp pandas beautifulsoup4 jinja2

      - name: Baixar e rodar o script
        run: |
          python extrair-portarias.py

      - name: Commit e push do arquivo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add portarias-anac.md portarias-anac.csv portarias-anac.html portarias-anac.json portarias-anac.tsv
          git commit -m "Atualizar portarias ANAC"
          git push