name: Portarias ANAC

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5' 
  
jobs:
  portarias:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v3

      - name: Configurar python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements-portaria.txt

      - name: Rodar o script
        run: |
          python scripts/portarias.py

      - name: Commit e push de arquivos, se houver mudanças
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          COMMIT_MESSAGE="Atualização: $(date +"%Y-%m-%d %H:%M")"
          git commit -m "$COMMIT_MESSAGE" || echo "Nada novo para commitar"
          git pull --rebase
          git push
