name: Portarias ANAC

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' 

jobs:
  portarias:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v4

      - name: Configurar python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp pandas beautifulsoup4 jinja2

      - name: Rodar o script
        run: |
          python scripts/portarias.py

      - name: Commit e push de arquivos, se houver mudanças
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add :/
          COMMIT_MESSAGE="$(date +"%Y-%m-%d %H:%M")"
          git commit -m "$COMMIT_MESSAGE" || exit 0
          git pull --rebase
          git push
