name: Portarias ANAC

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5' 
  
jobs:
  portarias:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v3

      - name: Configurar python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar o script
        run: |
          python portarias.py

      - name: Commit e push de arquivos, se houver mudanças
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          COMMIT_MESSAGE="Atualização - $(date +"%Y-%m-%d %H:%M")"
          git commit -m "$COMMIT_MESSAGE" || echo "Nada novo para commitar"
          git pull --rebase
          git push


#          if git diff-index --quiet HEAD; then
#            echo "Nenhuma mudança detectada. Finalizando a ação."
#            exit 0
#          else
#            COMMIT_MESSAGE="$(date +"%Y-%m-%d %H:%M")"
#            git commit -m "$COMMIT_MESSAGE" --allow-empty
#            git pull --rebase
#            git push
#          fi